Options for amino/nuc and to write fastest sites out
TheBrownLab/PhyloFisher pull request #109
Opened 2023-12-04 20:26 UTC by aguang

Options for amino/nuc and to write fastest sites out, #107

2023-12-05 16:36 UTC, robert-ervin-jones commented
Hi @aguang,

Thank you so much for your contribution. It looks like you are adding a new file named `fast_site_remover.py` to the repo's root directory rather than making changes to `fast_site_remover.py` in the `utilities` directory. Can you double-check this? If this is the case, can you fix the PR so that the original `fast_site_remover.py` is being updated rather than adding a new file? 

Thanks again! If you have any questions or concerns, please don't hesitate to reach out.

Best,
Robert

2023-12-14 18:29 UTC, aguang commented
Ah ok that's why it didn't appear to change the file (I tried to do it through uploading a file on the web interface). It should be fixed now, thank you!

2024-05-07 14:38 UTC, robert-ervin-jones requested changes
Can we change the model to GTR? Otherwise everything else looks good.

2024-05-07 14:38 UTC, robert-ervin-jones commented on phylofisher/utilities/fast_site_remover.py
> +    model = 2           * F81 (don't want to give rates for HKY/GTR...)
Can you change this to 7 (GTR)?

2024-05-07 14:40 UTC, robert-ervin-jones commented
Hi @aguang 

I apologize for just now getting back around to this.

Best,
Robert

2024-10-25 18:21 UTC, robert-ervin-jones approved these changes

2024-10-25 18:21 UTC, merged